### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by CaptSpify** [michael-lazar/rtv#94] opened 2015-04-23 05:47 UTC
kyelw@lappy ~ $ rtv
    Connecting...
    Traceback (most recent call last):
      File "/usr/local/bin/rtv", line 9, in <module>
        load_entry_point('rtv==1.3', 'console_scripts', 'rtv')()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
        ['__name__'])
      File "build/bdist.linux-x86_64/egg/rtv/__main__.py", line 135, in <module>
      File "build/bdist.linux-x86_64/egg/rtv/__main__.py", line 111, in main
      File "/usr/local/lib/python2.7/dist-packages/praw-2.1.21-py2.7.egg/praw/__init__.py", line 1331, in login
        self.request_json(self.config['login'], data=data)
      File "/usr/local/lib/python2.7/dist-packages/praw-2.1.21-py2.7.egg/praw/decorators.py", line 163, in wrapped
        return_value = function(reddit_session, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/praw-2.1.21-py2.7.egg/praw/__init__.py", line 565, in request_json
        data = json.loads(response, object_hook=hook)
      File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
        return cls(encoding=encoding, **kw).decode(s)
      File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded
    

Looks like it could be an issue with praw possibly?

**Comment by Brobin** [comment] 2015-04-23 06:09
Is username/password correct? It appears to be failing when attempting to login.

**Comment by michael-lazar** [comment] 2015-04-23 06:25
Yea PRAW seems to be having issues lately with logging in, see https://github.com/michael-lazar/rtv/issues/85 and https://github.com/praw-dev/praw/issues/353. Although your error looks slightly different from that one, you might want to try the fix suggested in the praw issue.

I'm using the same setup and it's working for me (python 2.7, praw 2.1.21, rtv 1.3).

**Comment by michael-lazar** [comment] 2015-04-30 05:22
Closing as unable to reproduce. Please feel free to reopen this or start a new issue if you have additional info to add.

**Closed by michael-lazar** 2015-04-30 05:22 UTC
