### ISSUE TITLE
ImportError - Installation fails both via pip and manual install

### ISSUE THREAD

**Issue by markphd** [michael-lazar/rtv#355] opened 2017-03-30 12:07 UTC
When doing installation via pip, I get:
ImportError: No module named '_curses'

Tried cloning the repo and run setup but I get:
ImportError: No module named setuptools

I even tried running `pip install -r requirements.txt` but didn't help.

Platform:
Python 2.7.12 (default, Oct 10 2016, 12:56:26)
[GCC 5.4.0] on cygwin
pip 9.0.1 from c:\users\administrator\appdata\local\programs\python\python35-32\lib\site
-packages (python 3.5)
Windows 7

**Comment by michael-lazar** [comment] 2017-03-30 15:13
People have had trouble with cygwin in the past, check out https://github.com/michael-lazar/rtv/issues/122

**Comment by michael-lazar** [comment] 2017-04-08 20:39
Closing because error is unconfirmed, please reopen if you have further information after trying the solutions posted in that issue

**Closed by michael-lazar** 2017-04-08 20:39 UTC
