### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by prithivraj** [michael-lazar/rtv#362] opened 2017-04-19 10:22 UTC
File "/usr/local/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/local/lib/python2.7/site-packages/rtv/__main__.py", line 178, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/rtv/__main__.py", line 108, in main
    encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 564, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

**Comment by michael-lazar** [comment] 2017-04-19 15:21
Looks like a duplicate of https://github.com/michael-lazar/rtv/issues/359 and https://github.com/michael-lazar/rtv/issues/339

**Closed** 2017-04-30 06:03 UTC
