### ISSUE TITLE
Viewing Submission Crashes rtv

### ISSUE THREAD

**Issue by notmar** [michael-lazar/rtv#462] opened 2017-10-23 22:30 UTC
rtv has been working great on this computer for the last couple of months. Today all of a sudden rtv started crashing whenever I try and view a submission.

`rtv -V`
outputs: rtv 1.17.1

Here is the error message that is echoed when it crashes:
```
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 11, in <module>
    load_entry_point('rtv==1.17.1', 'console_scripts', 'rtv')()
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/__main__.py", line 205, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/__main__.py", line 188, in main
    page.loop()
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/page.py", line 83, in loop
    self.controller.trigger(ch)
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/objects.py", line 594, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/subreddit_page.py", line 130, in open_submission
    self.reddit, self.term, self.config, self.oauth, url=url)
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/submission_page.py", line 30, in __init__
    max_comment_cols=config['max_comment_cols'])
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/content.py", line 344, in from_url
    submission = reddit.get_submission(url, comment_sort=order)
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/__init__.py", line 1107, in get_submission
    params=params)
  File "<decorator-gen-199>", line 2, in from_url
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/decorators.py", line 277, in wrap
    return function(*args, **kwargs)
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 1155, in from_url
    response = reddit_session.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/decorators.py", line 117, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/__init__.py", line 629, in request_json
    data = json.loads(response, object_hook=hook)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/__init__.py", line 487, in _json_reddit_objecter
    return object_class.from_api_response(self, json_data['data'])
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 55, in from_api_response
    return cls(reddit_session, json_dict=json_dict)
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 637, in __init__
    underscore_names=['replies'])
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 70, in __init__
    self._has_fetched = self._populate(json_dict, fetch)
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 179, in _populate
    setattr(self, name, value)
  File "/usr/local/Cellar/rtv/1.17.1/libexec/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 127, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
```

Any help would be appreciated.
-notmar

**Comment by mjbradford89** [comment] 2017-10-24 00:17
Getting the same error on version 1.18.0, Python 2.7.12, Ubuntu 16.04

**Comment by 8bitjoe** [comment] 2017-10-24 00:45
Same here with version 1.18.0-1, on Arch

**Comment by gagrilli** [comment] 2017-10-24 02:35
Slightly different here, with version 1.16,  python 3.4.6 on OpenSUSE Leap 42.3
Just before entering  a subreddit
```
Traceceback (most recent call last):                                                                             
  File "/usr/bin/rtv", line 7, in <module>                                                                     
    from rtv.__main__ import main                                                                              
  File "/usr/lib/python3.4/site-packages/rtv/__main__.py", line 200, in <module>                               
    sys.exit(main())                                                                                           
  File "/usr/lib/python3.4/site-packages/rtv/__main__.py", line 183, in main                                   
    page.loop()                                                                                                
  File "/usr/lib/python3.4/site-packages/rtv/page.py", line 83, in loop                                        
    self.controller.trigger(ch)                                                                                
  File "/usr/lib/python3.4/site-packages/rtv/objects.py", line 594, in trigger                                 
    return func(self.instance, *args, **kwargs)                                                                
  File "/usr/lib/python3.4/site-packages/rtv/subreddit_page.py", line 123, in open_submission                  
    self.reddit, self.term, self.config, self.oauth, url=url)                                                  
  File "/usr/lib/python3.4/site-packages/rtv/submission_page.py", line 30, in __init__                         
    max_comment_cols=config['max_comment_cols'])                                                               
  File "/usr/lib/python3.4/site-packages/rtv/content.py", line 343, in from_url                                
    submission = reddit.get_submission(url, comment_sort=order)                                                
  File "/usr/lib/python3.4/site-packages/rtv/packages/praw/__init__.py", line 1107, in get_submission          
    params=params)                                                                                             
  File "<decorator-gen-199>", line 2, in from_url                                                              
  File "/usr/lib/python3.4/site-packages/rtv/packages/praw/decorators.py", line 277, in wrap                   
    return function(*args, **kwargs)                                                                           
  File "/usr/lib/python3.4/site-packages/rtv/packages/praw/objects.py", line 1155, in from_url                 
    response = reddit_session.request_json(url, params=params)                                                 
  File "<decorator-gen-8>", line 2, in request_json                                                            
  File "/usr/lib/python3.4/site-packages/rtv/packages/praw/decorators.py", line 117, in raise_api_exceptions   
    return_value = function(*args, **kwargs)                                                                   
  File "/usr/lib/python3.4/site-packages/rtv/packages/praw/__init__.py", line 629, in request_json             
    data = json.loads(response, object_hook=hook)                                                              
  File "/usr/lib64/python3.4/json/__init__.py", line 331, in loads                                             
    return cls(**kw).decode(s)                                                                                 
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode                                             
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                          
  File "/usr/lib64/python3.4/json/decoder.py", line 359, in raw_decode                                         
    obj, end = self.scan_once(s, idx)                                                                          
  File "/usr/lib/python3.4/site-packages/rtv/packages/praw/__init__.py", line 487, in _json_reddit_objecter    
    return object_class.from_api_response(self, json_data['data'])                                             
  File "/usr/lib/python3.4/site-packages/rtv/packages/praw/objects.py", line 55, in from_api_response          
    return cls(reddit_session, json_dict=json_dict)                                                            
  File "/usr/lib/python3.4/site-packages/rtv/packages/praw/objects.py", line 637, in __init__                  
    underscore_names=['replies'])                                                                              
  File "/usr/lib/python3.4/site-packages/rtv/packages/praw/objects.py", line 70, in __init__                   
    self._has_fetched = self._populate(json_dict, fetch)                                                       
  File "/usr/lib/python3.4/site-packages/rtv/packages/praw/objects.py", line 179, in _populate                 
    setattr(self, name, value)                                                                                 
  File "/usr/lib/python3.4/site-packages/rtv/packages/praw/objects.py", line 127, in __setattr__               
    object.__setattr__(self, name, value)                                                                      
AttributeError: can't set attribute
```
But stopping at the same module, looking for my session attributes
Also started today.

Anything I can do to help or whatever, feel free to ask. Thank you for a great command line program.

**Comment by sealevelcain** [comment] 2017-10-24 02:36
Same here, macOS 10.12.6/rtv 1.16

**Comment by effendijohanes** [comment] 2017-10-24 02:50
same here, mac os 10.12.6, python 3.6.2, rtv 1.18.0

**Comment by VioletVivirand** [comment] 2017-10-24 04:00
+1, Meet this issue also.

Environment Spec:

* rtv version (`rtv -V`): *1.18.0*
* Python version:
    * `python --version`: *2.7.11*
    * `python --version`: *3.6.0* (BTW, how do I know if rtv is executed with Python v2 or v3?)
* Mac OS version: Sierra *10.12.6*

Situation Reproduce:

Visit [this Submission](https://www.reddit.com/r/NintendoSwitch/comments/788xcx/the_switch_is_going_to_be_some_childrens_first/) in [/r/NintendoSwitch](https://www.reddit.com/r/NintendoSwitch/), and rtv returns:

```python
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/rtv/__main__.py", line 221, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/rtv/__main__.py", line 204, in main
    page.loop()
  File "/usr/local/lib/python3.6/site-packages/rtv/page.py", line 83, in loop
    self.controller.trigger(ch)
  File "/usr/local/lib/python3.6/site-packages/rtv/objects.py", line 621, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rtv/subreddit_page.py", line 157, in open_link
    self.open_submission()
  File "/usr/local/lib/python3.6/site-packages/rtv/subreddit_page.py", line 136, in open_submission
    self.reddit, self.term, self.config, self.oauth, url=url)
  File "/usr/local/lib/python3.6/site-packages/rtv/submission_page.py", line 31, in __init__
    max_comment_cols=config['max_comment_cols'])
  File "/usr/local/lib/python3.6/site-packages/rtv/content.py", line 344, in from_url
    submission = reddit.get_submission(url, comment_sort=order)
  File "/usr/local/lib/python3.6/site-packages/rtv/packages/praw/__init__.py", line 1107, in get_submission
    params=params)
  File "<decorator-gen-199>", line 2, in from_url
  File "/usr/local/lib/python3.6/site-packages/rtv/packages/praw/decorators.py", line 277, in wrap
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 1155, in from_url
    response = reddit_session.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/lib/python3.6/site-packages/rtv/packages/praw/decorators.py", line 117, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rtv/packages/praw/__init__.py", line 629, in request_json
    data = json.loads(response, object_hook=hook)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/local/lib/python3.6/site-packages/rtv/packages/praw/__init__.py", line 487, in _json_reddit_objecter
    return object_class.from_api_response(self, json_data['data'])
  File "/usr/local/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 55, in from_api_response
    return cls(reddit_session, json_dict=json_dict)
  File "/usr/local/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 637, in __init__
    underscore_names=['replies'])
  File "/usr/local/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 70, in __init__
    self._has_fetched = self._populate(json_dict, fetch)
  File "/usr/local/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 179, in _populate
    setattr(self, name, value)
  File "/usr/local/lib/python3.6/site-packages/rtv/packages/praw/objects.py", line 127, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
```

**Comment by michael-lazar** [comment] 2017-10-24 04:13
It looks like Reddit recently changed their API response in a way that broke the python API wrapper.

https://www.reddit.com/r/redditdev/comments/78bgvn/praw_has_reddit_changed_the_api_in_such_a_way/

This project uses a forked version of PRAW (https://github.com/michael-lazar/praw3) so unfortunately we can't rely on this being fixed upstream. I'm looking into possible fixes, but it's late here so I might not be able to get to this tonight. Will post updates as I find them.

**Comment by michael-lazar** [comment] 2017-10-24 04:48
A fix has been applied to the master branch. To test, you can run

```
pip install -U git+git://github.com/michael-lazar/rtv.git@master
```

I'll work on publishing a new release to PyPI within the next 24 hours. I don't want to rush it in case other breaking errors are discovered.

**Comment by gagrilli** [comment] 2017-10-24 05:17
Running rtv from the master branch with the fix applied seems to solve the issue.  Smooth sailing, and probably because of 2-3 pip upgrades, a lot faster too!!   

Thanks for such a prompt responce and efective solution!

**Comment by jwpincus** [comment] 2017-10-24 18:07
The homebrew formula doesn't seem to be pulling down the latest...

**Comment by mjbradford89** [comment] 2017-10-24 19:10
Running the latest from master seems to have fixed the issue. :+1:

**Comment by jwpincus** [comment] 2017-10-24 20:17
From what I understand homebrew doesn't pull from master, rather there's a recipe that specifies a gzipped tar and that is what needs to be brought up to date by someone who has permissions or knowledge of that

**Comment by da7id** [comment] 2017-10-24 21:20
Echoing what @jwpincus , is there a timeline to get this updated in Homebrew?

**Comment by michael-lazar** [comment] 2017-10-24 22:15
A new version has now been released and uploaded to PyPI:

https://github.com/michael-lazar/rtv/releases/tag/v1.19.0

Anyone who installed through pip can now run:
```
pip install rtv --upgrade
```

It will be up to the package maintainers or other volunteers to update homebrew, etc. Since prior versions are totally broken now there should be a strong motivation to upgrade to the latest version.

**Comment by da7id** [comment] 2017-10-24 22:17
Who has done that in the past? I’d be happy to help get the home brew instance updated

**Comment by jwpincus** [comment] 2017-10-24 23:04
I've got a PR up to update the brew formula. https://github.com/Homebrew/homebrew-core/pull/19807 

You can manually change the formula with that code on your local machine if you don't want to wait

**Comment by zethra** [comment] 2017-10-25 05:10
I had this problem in version 1.18 but it was fixed in 1.19

**Comment by KathrynN** [comment] 2017-10-25 12:40
Updating the brew formula manually as per jwpincus works while we wait for the PR to be changed and approved.

**Comment by southpaw5271** [comment] 2017-10-25 15:24
Can confirm jwpincus' update fixed the issue.

**Comment by michael-lazar** [comment] 2017-10-25 18:18
Reddit has reverted their API change, older versions of RTV should now be working again:

https://www.reddit.com/r/redditdev/comments/78bgvn/praw_has_reddit_changed_the_api_in_such_a_way/dovfq4e/

I still recommend that users upgrade to the latest version 1.19.0 , but this is no longer a critical issue.

**Comment by D0cR3d** [comment] 2017-10-27 00:40
They changed things again https://www.reddit.com/r/changelog/comments/78y3wp/comment_models_returned_by_the_api_will_have/

**Comment by michael-lazar** [comment] 2017-10-27 01:45
sigh

**Comment by jwpincus** [comment] 2017-10-27 23:54
The good news is my version change was merged into homebrew and now goes to version 1.19, which still works as of now; so you got that goin for you, which is nice...

**Comment by noahfx** [comment] 2017-10-29 15:48
Hi, 
FYI:  I have uploaded version 1.19.0 to the Debian Unstable suite, it will be migrated to Testing suite in about 5 days from now, and I guess it will be in Ubuntu Universe in about 2 weeks more or less.

**Closed** 2017-11-04 19:34 UTC
Labels: bug

**Comment by SaphiraTa** [comment] 2018-01-06 03:32
Also still having this issue. My output looks like this every time I try to load comments 
Traceback (most recent call last):
  File "/usr/bin/rtv", line 11, in <module>
    load_entry_point('rtv==1.17.1', 'console_scripts', 'rtv')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/rtv/__main__.py", line 205, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/rtv/__main__.py", line 188, in main
    page.loop()
  File "/usr/lib/python3/dist-packages/rtv/page.py", line 83, in loop
    self.controller.trigger(ch)
  File "/usr/lib/python3/dist-packages/rtv/objects.py", line 594, in trigger
    return func(self.instance, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/rtv/subreddit_page.py", line 130, in open_submission
    self.reddit, self.term, self.config, self.oauth, url=url)
  File "/usr/lib/python3/dist-packages/rtv/submission_page.py", line 30, in __init__
    max_comment_cols=config['max_comment_cols'])
  File "/usr/lib/python3/dist-packages/rtv/content.py", line 344, in from_url
    submission = reddit.get_submission(url, comment_sort=order)
  File "/usr/lib/python3/dist-packages/rtv/packages/praw/__init__.py", line 1107, in get_submission
    params=params)
  File "<decorator-gen-199>", line 2, in from_url
  File "/usr/lib/python3/dist-packages/rtv/packages/praw/decorators.py", line 277, in wrap
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/rtv/packages/praw/objects.py", line 1155, in from_url
    response = reddit_session.request_json(url, params=params)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/lib/python3/dist-packages/rtv/packages/praw/decorators.py", line 117, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/rtv/packages/praw/__init__.py", line 629, in request_json
    data = json.loads(response, object_hook=hook)
  File "/usr/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/lib/python3/dist-packages/rtv/packages/praw/__init__.py", line 487, in _json_reddit_objecter
    return object_class.from_api_response(self, json_data['data'])
  File "/usr/lib/python3/dist-packages/rtv/packages/praw/objects.py", line 55, in from_api_response
    return cls(reddit_session, json_dict=json_dict)
  File "/usr/lib/python3/dist-packages/rtv/packages/praw/objects.py", line 637, in __init__
    underscore_names=['replies'])
  File "/usr/lib/python3/dist-packages/rtv/packages/praw/objects.py", line 70, in __init__
    self._has_fetched = self._populate(json_dict, fetch)
  File "/usr/lib/python3/dist-packages/rtv/packages/praw/objects.py", line 179, in _populate
    setattr(self, name, value)
  File "/usr/lib/python3/dist-packages/rtv/packages/praw/objects.py", line 127, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

**Comment by michael-lazar** [comment] 2018-01-06 04:03
@SaphiraTa you need to upgrade to the latest version of rtv through your package manager or using ``pip``, depending on how you installed rtv.
