### ISSUE TITLE
[Bug] No Backspace Capability when Typing a Subreddit

### ISSUE THREAD

**Issue by mekhami** [michael-lazar/rtv#4] opened 2015-03-02 15:29 UTC
Currently can't backspace when entering a subreddit in the prompt. Small bug, I imagine.

**Comment by michael-lazar** [comment] 2015-03-02 18:01
Works for me in gnome-terminal, what terminal are you using?

**Comment by mekhami** [comment] 2015-03-02 18:47
Not working in iterm2 for os x

**Comment by mishravikas** [comment] 2015-03-02 23:25
Not working on xfce4-terminal 0.6.3

**Comment by michael-lazar** [comment] 2015-03-02 23:47
It actually works for me on a fresh install of xfce4-terminal 0.6.3. Try going to preferences -> compatability and check what the backspace key is set to. **curses** expects control-h (^h). My guess is that iterm2 has a similar issue, but I'm unable to check because I don't have a Mac.

From the curses documentation
```
    """Editing widget using the interior of a window object.
     Supports the following Emacs-like key bindings:

    Ctrl-A      Go to left edge of window.
    Ctrl-B      Cursor left, wrapping to previous line if appropriate.
    Ctrl-D      Delete character under cursor.
    Ctrl-E      Go to right edge (stripspaces off) or end of line (stripspaces on).
    Ctrl-F      Cursor right, wrapping to next line when appropriate.
    Ctrl-G      Terminate, returning the window contents.
    Ctrl-H      Delete character backward.
    Ctrl-J      Terminate if the window is 1 line, otherwise insert newline.
    Ctrl-K      If line is blank, delete it, otherwise clear to end of line.
    Ctrl-L      Refresh screen.
    Ctrl-N      Cursor down; move down one line.
    Ctrl-O      Insert a blank line at cursor location.
    Ctrl-P      Cursor up; move up one line.

    Move operations do nothing if the cursor is at an edge where the movement
    is not possible.  The following synonyms are supported where possible:

    KEY_LEFT = Ctrl-B, KEY_RIGHT = Ctrl-F, KEY_UP = Ctrl-P, KEY_DOWN = Ctrl-N
    KEY_BACKSPACE = Ctrl-h
```

**Comment by ragreener1** [comment] 2015-03-04 17:05
I can confirm it doesn't work on iTerm 2

**Comment by ragreener1** [comment] 2015-03-04 17:12
I think iTerm 2 uses ^? as the backspace key (http://www.macfreek.nl/memory/Backspace_and_Delete_key_reversed#iTerm_.28Mac_OS_X_application.29)

**Comment by michael-lazar** [comment] 2015-03-04 18:31
So looking through the curses textpad source there are two supported keys for backspace
* `curses.ascii.BS` which is mapped to `0x08` (^H)
* `curses.KEY_BACKSPACE` which is mapped to `0x107`

It's seems very strange that `curses.ascii.DEL` which is mapped to `0x7F` (^?) is not supported. From the link that you posted that seems to the the standard convention. Sure enough, when I type ctrl-v and press the backspace key, it prints ^? in my terminal.

**Comment by michael-lazar** [comment] 2015-03-05 07:58
I still don't understand exactly what's causing this, but I pushed a patch 7738211 to convert `0x7f` to a backspace. Please let me know if this fixes the problem for you.

**Comment by peterpans01** [comment] 2015-03-05 09:17
I try on Windows but it didn't work,too. (Tested after the patch 7738211). And the character after ''Enter Subreddit: /r/" is invisible (maybe it's black!).

**Comment by peterpans01** [comment] 2015-03-05 10:57
Sorry, I'm just beginner of curses. After typing the name of subreddit, how can I access it? ENTER key didn't work.

**Comment by tobywhughes** [comment] 2015-03-05 11:24
What do you mean by it is invisible? As in, if the text was "/r/python" it shows as "/r/ ython"?

**Comment by peterpans01** [comment] 2015-03-05 11:55
No, I mean I can see the cursor change the position but I can't see the text I typed.

**Comment by michael-lazar** [comment] 2015-03-05 18:09
Hi @peterpans01, thanks for the heads up.

Did you have to do anything special to get this to work in Windows? According to https://docs.python.org/3.3/howto/curses.html, curses is not included in the Windows version of Python. I'm honestly surprised that this is working for you at all.

My guess is that whatever curses build that you're using has different behavior for some functions, namely this one https://docs.python.org/2/library/curses.html#curses.window.addch. I'll try it out on my Windows box when I get home today.

**Comment by Qu4tro** [comment] 2015-03-05 20:12
Just informing that it works fine on xterm.

**Comment by peterpans01** [comment] 2015-03-06 05:13
Hi @michael-lazar, it's not so special. I just need to install curses in windows and it's works. :dancer:  You can try intall curses here: http://www.lfd.uci.edu/~gohlke/pythonlibs/#curses. I'm still looking for a solution for that.

**Comment by tobywhughes** [comment] 2015-03-06 21:59
Is it possible that rtv could install curses automatically if an installation is not found?

**Comment by peterpans01** [comment] 2015-03-07 14:47
I confirm that backspace works in Windows 7 and I can fix the errors I show above.

**Comment by michael-lazar** [comment] 2015-03-08 07:15
Resolved in https://github.com/michael-lazar/rtv/pull/31. Thanks again for looking into this @peterpans01. Once things have settled down a bit, I'll add a section in the README with instructions for installing curses on Windows.

**Closed by michael-lazar** 2015-03-08 07:15 UTC
Labels: bug
