### ISSUE TITLE
Non-Ascii characters

### ISSUE THREAD

**Issue by yskmt** [michael-lazar/rtv#23] opened 2015-03-05 20:00 UTC
I know that encoding is a sensitive issue, but is there a reason that you convert unicode string to ascii in `clean` function? That makes non-ascii characters (Japanese, Chinese, Korean, Arabic, Emoji, etc) not rendered.

For example, adding the following line in the beginning 

    import locale
    locale.setlocale(locale.LC_ALL, '')

and changing encoding in `clean` function to something like this

    utf8_string = unicode_string.encode('utf-8', 'replace')

make non-ascii characters rendered on the console.

**Comment by michael-lazar** [comment] 2015-03-06 01:46
I think this is a fair point, I don't have anything against adding unicode. I went with ASCII because I was worried about compatibility with terminal emulators and different system configurations lacking unicode support.

**Comment by michael-lazar** [comment] 2015-03-10 22:48
https://github.com/michael-lazar/rtv/pull/33

**Comment by michael-lazar** [comment] 2015-03-11 05:29
Fixed pull request in 47ad49a189ce268d905c99229a05cfd62c7a4b0d.

However, there still appear to be some issues with python3. For example,
```
$ python2 -m rtv -l http://www.reddit.com/r/LearnJapanese/comments/2ylsz9/request_japanese_audio_textbook_audiobook_or/ --force-ascii
```
loads correctly, but

```
$ python3 -m rtv -l http://www.reddit.com/r/LearnJapanese/comments/2ylsz9/request_japanese_audio_textbook_audiobook_or/ --force-asci
```
crashes with the following error
```python
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/michael/Projects/rtv_project/rtv/__main__.py", line 7, in <module>
    main()
  File "/home/michael/Projects/rtv_project/rtv/main.py", line 84, in main
    page.loop()
  File "/home/michael/Projects/rtv_project/rtv/submission.py", line 28, in loop
    self.draw()
  File "/home/michael/Projects/rtv_project/rtv/page.py", line 143, in draw
    self._draw_content()
  File "/home/michael/Projects/rtv_project/rtv/page.py", line 194, in _draw_content
    attr = self.draw_item(subwindow, data, inverted)
  File "/home/michael/Projects/rtv_project/rtv/submission.py", line 95, in draw_item
    return self.draw_comment(win, data, inverted=inverted)
  File "/home/michael/Projects/rtv_project/rtv/submission.py", line 122, in draw_comment
    win.addnstr(row, 1, text, n_cols-1)
_curses.error: addnwstr() returned ERR
```
Passing ``--force-ascii`` fixes the crash, but I would like to figure out why some unicode characters appear to be messing with curses in python3.4.

**Comment by ragreener1** [comment] 2015-03-11 21:09
That doesn't make a lot of sense because this works http://www.reddit.com/r/LearnJapanese/comments/2yonx8/is_there_any_difference_between_%E9%87%8D%E3%81%9F%E3%81%84_and_%E9%87%8D%E3%81%84/ and that has japanese characters in it

**Comment by michael-lazar** [comment] 2015-03-12 07:22
I did some investigating into this! It looks like the problem is with how python3 **curses.addnstr()** calculates the *n*.  The expected behavior is that **curses.addnstr(y, x, text, n)** will print the first *n* characters of the*text* string onto the screen. Here's what's happening.

```python3
import curses
import locale
locale.setlocale(locale.LC_ALL, '')

def func(stdscr):

    stdscr.clear()

    text = 'a' * 5
    stdscr.addnstr(0, 0, text, 6)
    stdscr.addnstr(1, 0, text, 5)
    stdscr.addnstr(2, 0, text, 4)

    text = 'あ' * 5
    stdscr.addnstr(4, 0, text, 6)
    stdscr.addnstr(5, 0, text, 5)
    stdscr.addnstr(6, 0, text, 4)

    text = ('あ' * 5).encode('utf-8')
    stdscr.addnstr(8, 0, text, 6)
    stdscr.addnstr(9, 0, text, 5)
    stdscr.addnstr(10, 0, text, 4)


    stdscr.refresh()
    stdscr.getch()
    stdscr.getch()

if __name__ == '__main__':
    curses.wrapper(func)
```

![screenshot from 2015-03-12 00 00 35](https://cloud.githubusercontent.com/assets/5026795/6613512/92cfc88a-c84b-11e4-98d4-6064b0d0064f.png)

1. Passing unicode characters within ordinal range(128) works as expected, each character takes up one column of the terminal and up to *n* characters are printed.
2. Passing unicode characters outside of the ordinal range(128). Up to n characters are printed, but each character takes up two columns in the terminal. So unless we know exactly how much space each character takes, passing in a value for *n* becomes useless for any practical sense.
3. Passing utf-8 encoded bytes. Now this one is odd, it looks like *n* is counting the number of **bytes** passed in. The 'あ' character is 3-bytes long in utf-8. Setting *n* to 6 allows for 6/3=2 full characters to be printed. Setting *n* below six cuts off the final character. It is unclear what happens to the partial character bytes. This mode is also practically useless because it doesn't account for the width of each character on the screen.

**Comment by michael-lazar** [comment] 2015-03-12 07:25
I don't know if if there is a good way to handle this.

I didn't realize that some unicode characters take up more space than others. This will break how I am currently using [textwrap](https://docs.python.org/3.1/library/textwrap.html) to format paragraphs to fit on the page.

**Comment by yskmt** [comment] 2015-03-12 22:52
Yes. I observed too that sometimes a unicode character breaks at the line-change.

**Comment by michael-lazar** [comment] 2015-03-13 02:25
Heads up, I changed the default encoding to ascii until this is resolved. 7db8c2f

**Comment by michael-lazar** [comment] 2015-03-13 02:51
Interesting reading on the subject http://stackoverflow.com/questions/3634627

**Comment by michael-lazar** [comment] 2015-03-14 07:31
I've refactored the code to follow the "unicode sandwich" design method described [here](http://nedbatchelder.com/text/unipain/unipain.html#35). This should make the problem easier to address in the future while considering both py2 and py3.

**Comment by firecat53** [comment] 2015-03-30 13:43
We used unicodedata.east_asian_width to help calculate column widths for my [curses CSV viewer](https://github.com/firecat53/tabview/blob/master/tabview/tabview.py).

**Comment by michael-lazar** [comment] 2015-05-15 03:12
Hey guys! I just merged a large update to the master branch that will hopefully smooth out all of the unicode issues in the codebase. We are now using the [kitchen](https://pypi.python.org/pypi/kitchen) python package, which provides a bunch of unicode-aware text formatting [functions](http://pythonhosted.org//kitchen/api-text-display.html). I also set the default program mode to enable unicode, with the option to disable it with the ``--ascii`` flag. 

@yskmt do you think you could help me test this out, or point me to some non-english subreddits? I would really appreciate it.

**Comment by yskmt** [comment] 2015-05-20 01:27
@michael-lazar Sure. Have you implemented it? Is it on master branch?

**Comment by michael-lazar** [comment] 2015-05-20 02:07
Yes it is currently on master. Unicode mode should be turned on by default, so all you have to do is checkout master and run it.

**Comment by michael-lazar** [comment] 2015-06-05 05:18
I haven't heard any objections so I'm closing this for now. If anybody discovers a problem, please open a new issue.

**Closed by michael-lazar** 2015-06-05 05:18 UTC
