### ISSUE TITLE
ConnnectionError when computer waked from suspend

### ISSUE THREAD

**Issue by sunng87** [michael-lazar/rtv#192] opened 2016-02-02 02:58 UTC
I'm on rtv 1.8.0 and I keep rtv opened constantly. One issue is when I suspend my computer and wake up, I have to quit rtv and start it again. Otherwise I will get `ConnectionError` on any move. 

I think it might because rtv keeps the connection at background for reuse. But it would be great to add retry mechanism on such `ConnectionError`.

**Comment by michael-lazar** [comment] 2016-02-02 17:32
Thanks for posting the issue, that's an interesting use-case that I haven't come across yet,

**Comment by michael-lazar** [comment] 2016-08-03 04:32
Closing because it's been several months and I haven't been able to reproduce this error. If anybody has any further info, feel free to reopen.

**Closed by michael-lazar** 2016-08-03 04:32 UTC
Labels: bug
